#!/bin/sh

export IOCSH_PS1="acq400-epics>"
ETOP=/usr/local/epics
STCMD=/tmp/st.cmd
PIDF=/var/run/acq400ioc.pid
GXPID=/var/run/gain_all_x.pid
LOG=/var/log/epics.log
NICE=10
LG="logger -t acq400ioc.init"
RL=/tmp/records.dbl


if [ -f /etc/profile.d/epics.sh ]; then
	source /etc/profile.d/epics.sh
fi
if [ -f /mnt/local/epics.sh ]; then
	source /mnt/local/epics.sh
fi
if [ -f /mnt/local/sysconfig/epics.sh ]; then
	if [ -z $EPICS_LOCAL_SYSCONFIG ]; then 
		source /mnt/local/sysconfig/epics.sh
		(
			grep ^export /mnt/local/sysconfig/epics.sh
			[ -z $IOC_HOST ] && echo export IOC_HOST=$(hostname)
			echo export EPICS_LOCAL_SYSCONFIG=1
		) >> /etc/profile.d/epics.sh
	fi
else
	echo "WARNING: file /mnt/local/sysconfig/epics.sh missing"
fi

ACQ400IOC=/usr/local/bin/acq400ioc
if [ -e /mnt/local/acq400ioc ]; then
	ACQ400IOC=/mnt/local/acq400ioc
	echo use patch IOC $ACQ400IOC
fi

source /tmp/u-boot_env
HOST=${IOC_HOST:-$(hostname)}
MB_MODEL=$(basename ${devicetree_image%*.dtb})

source /usr/local/epics/scripts/init_support.sh
source /usr/local/epics/scripts/init_make_knobs.sh

if [ ! -e $LOG ]; then
	grep -q emlog /proc/modules; [ $? -ne 0 ] && /sbin/insmod /usr/local/lib/modules/emlog.ko
        [ -e $LOG ] || mkemlog $LOG 16
fi

wait_ioc_records_loaded() {
	let pollcat=0;
	while [ ! -e "$RL.done" ]; do
		let report=$pollcat%5
		if [ $report -eq 0 ]; then
			$LG wait_ioc_records_loaded $pollcat
		fi
		sleep 1
		let pollcat="$pollcat+1"
	done	
}


make_stcmd() {
	if [ ! -e ${STCMD} ]; then (
		echo "++ create EPICS db ${STCMD}" 
		cd ${ETOP}
		./scripts/extract_gains
		./scripts/load.records > ${STCMD}
	) fi
	for file in /usr/local/epics/init.d/*.init_final
	do
		if [ -x $file ]; then
			echo 1>&2 "execute extension $file"
			$file
		elif [ -e $file ]; then
			echo 1>&2 "source extension $file"
			source $file
		fi 
	done
	cat - >> ${STCMD} <<EOF
dbLoadRecords("db/local-aliases.db","UUT=${HOST}")
iocInit()	
dbl > ${RL}
seqShow > ${RL}.done
EOF
}

make_aliases_loop() {
	while read PV
	do
		echo alias\(\"$PV\",\"$1:${PV#*:}\"\)
	done
}
make_aliases() {
	make_aliases_loop $1 <$RL >/usr/local/epics/db/local-aliases.db	 
}

bump() 
{
	echo X | tr X \\030 | acq4xx-epics-console >/dev/null
}

start_ioc() {
	/usr/local/bin/procServ \
		-c ${ETOP} -p $PIDF -L $LOG 2222 \
		/bin/nice -n $NICE ${ACQ400IOC} ${STCMD}
	while [ ! -r $PIDF ]; do
		usleep 10000
	done
	$LG start_ioc PID $(cat $PIDF) ioc $(pidof acq400ioc)
}

stop_ioc() {
	if [ -r ${PIDF} ]; then
		$LG stop_ioc PID $(cat $PIDF)
		kill -s TERM $(cat ${PIDF})
		rm ${PIDF}
	fi
}


stop_gain_all_x_svc() {
        if [ -r ${GXPID} ]; then
                kill -s TERM $(cat ${GXPID})
                rm ${GXPID}
        fi
}

start_gain_all_x_svc() {
        source /etc/profile.d/epics.sh
        stop_gain_all_x_svc
        /usr/local/bin/procServ -p $GXPID 2228 /usr/local/epics/scripts/gain_all_x_svc.py
}



wait_ntp() {
        if [ -z $IOC_WAIT_NTP ] || [ "$IOC_WAIT_NTP" = "0" ]; then
                return
        fi

        while [ $IOC_WAIT_NTP -gt 0 ]; do
                year=$(date +%Y)
                if [ $year -lt 2025 ]; then
                        $LG waiting for NTP
                        sleep $IOC_WAIT_NTP
			IOC_WAIT_NTP=$((IOC_WAIT_NTP-1))
                else
                        break
                fi
        done
        $LG NTP good
}


restart() {
	if [ "$1" = "force" ]; then
		rm -f ${STCMD}
	fi	
	make_stcmd
	wait_ntp
	stop_ioc
	start_ioc
	wait_ioc_records_loaded
	stop_ioc
	nice /usr/local/init/acq400ioc.init make_epics_knobs
        [ "x$GAIN_ALL_X" = "xy" ] && [ -e /etc/acq400/0/gain_all_x ] && start_gain_all_x_svc&

	[ "x$IOC_GLOBAL_ALIAS_PFX" != "x" ] && make_aliases $IOC_GLOBAL_ALIAS_PFX
	cat /tmp/st_final.cmd >> /tmp/st.cmd
	start_ioc
}


case "$1" in
bump)
	bump;;
forcestart)
	restart force;;
start|"")
	restart;;
stop)
	stop_ioc;;
suspend)
	kill -STOP $(pidof acq400ioc);;
resume)
	kill -CONT $(pidof acq400ioc);;
make_epics_knobs)
	sleep 1; 
	echo "+++ make_epics_knobs"
	make_epics_knobs;;
*)
	echo 'usage acq400ioc.init start|stop|forcestart|suspend|resume';;
esac
